{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.env }}-{{ .Values.name }}
spec:
  refreshInterval: "5s"
  secretStoreRef:
    name: {{ .Values.secretStoreRef.name }}
    kind: ClusterSecretStore
  target:
    name: {{ .Values.env }}-{{ .Values.name }}
  dataFrom:
    - extract:
        key: {{ .Values.env }}-{{ .Values.name }}
{{- end }}